# Machine Learning Libraries

In [1]:
#Some of the machine libraries are as follows:
### Numpy 
### Pandas
### Matplotlib
### Seaborn
### Sipy
### sklearn

In [2]:
import numpy as np

### np is alias
### we can write anything in place of np as alias

In [3]:
### 1st method to create an array

simple_list=[6,7,8]
np.array(simple_list)

array([6, 7, 8])

In [4]:
##2nd method to create an array

arr=np.array([6,7,8])
arr

array([6, 7, 8])

In [5]:
type(arr)

numpy.ndarray

In [6]:
### lists within the list


list_of_lists=([1,2,3],[4,5,6],[7,8,9])
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [8]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

###  np.arange
### step size is 1
### last one is not included for example np.arange(2,10) its from 2 to 9


In [9]:
np.arange(5,28)

## step size is 1
# starts with 5
# ends with 27

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27])

In [10]:
np.arange(5,35,6)

### starts with 5
### ends with 34, but as step size is 6 the last element is 35
### by default step size is one 
### we can define step size in 3rd argument


array([ 5, 11, 17, 23, 29])

### np.zeros
### elements data type is float by default
### all elements are 0
### number of zeros are given as first argument in parathesis

In [11]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros(6,dtype=int)

### data type is mentioned in the second argument
## all zeros are int type

array([0, 0, 0, 0, 0, 0])

In [13]:
np.zeros((2,3),dtype=int)

### 2 rows and 3 columns

array([[0, 0, 0],
       [0, 0, 0]])

### np.ones
### elements data type is float by default
### all elements are 1
### number of ones are given as first argument in parathesis

In [14]:
np.ones(5)


array([1., 1., 1., 1., 1.])

In [15]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [16]:
np.ones((4,8))
## 4 rows and 8 columns
### all floats

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
np.ones((4,8),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

### np.linspace
### Number of samples to generate. Default is 50. Must be non-negative.
### step size is given in 3rd arguement, bydefault its 50

In [18]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [19]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [20]:
np.linspace(0,10,num=9 )

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [21]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [22]:
np.arange(0,20,10)

array([ 0, 10])

### np.eye 
### identity matrix
### takes single argument are number of rows n colums
### np.eye(5) gives identity matrix of 5 rows n columns
### default data type is float


In [23]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [24]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [25]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### np.random.rand(2,4)
### 2 rows and 4 coulmns
### always gives random values ranging betweeen 0 to 1
### uniform distribution
### only positive values


In [26]:
np.random.rand(2,4)

array([[0.81948327, 0.00778997, 0.6733033 , 0.51334028],
       [0.88962792, 0.14433324, 0.54816104, 0.550825  ]])

### np.random.randn(2,4)
### 2 rows and 3 columns
### random values ranging -1 to 1
### standard normal distribution

In [27]:
np.random.randn(2,3)

array([[ 0.585138  , -0.94572702,  0.23750681],
       [-0.79409488, -0.07031328, -0.79238264]])

### np.random.randint(2,20,100)
### starts with 2
### ends with 19
### number of samples in 100
### all random values and values are allowed to be repeated

In [28]:
np.random.randint(2,20,100)

array([16, 14, 13,  6, 19, 14,  9,  7, 17,  9, 18, 19, 19, 14, 13,  9,  9,
       14, 18,  3, 11, 17,  6,  8,  7,  8,  6, 11, 15, 12, 18,  8,  6, 15,
       16, 10, 11, 16, 16,  8, 17,  7, 11, 19,  8,  4, 10,  8, 13,  5, 16,
       18, 16, 15, 15, 18, 13, 19,  2, 13, 13, 14, 13, 13,  6, 11, 12, 15,
       14, 18,  5,  2,  2, 12, 12, 11,  2, 16,  7,  4, 15,  3,  8, 13, 19,
       12, 16, 18,  8,  9, 16, 16,  5, 19, 12,  2, 18, 10, 15,  6])

In [29]:
np.random.randint(10,100,15)


array([99, 64, 96, 46, 42, 34, 72, 78, 21, 41, 29, 78, 43, 36, 68])

In [30]:
np.random.randint(20,56,100)

array([42, 24, 47, 23, 40, 39, 34, 39, 32, 51, 31, 40, 46, 20, 45, 28, 44,
       25, 47, 53, 29, 26, 34, 38, 49, 34, 47, 51, 41, 35, 22, 51, 50, 30,
       30, 32, 45, 52, 33, 49, 29, 42, 25, 36, 41, 53, 55, 27, 20, 49, 22,
       24, 50, 26, 31, 51, 21, 50, 27, 45, 27, 25, 42, 48, 25, 20, 32, 36,
       22, 24, 55, 31, 44, 23, 33, 40, 49, 21, 37, 32, 28, 36, 20, 42, 40,
       51, 34, 37, 52, 46, 30, 50, 50, 29, 54, 42, 55, 48, 37, 30])

In [31]:
sample_array=np.arange(2,20)

In [32]:
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [33]:
rand_array=np.random.randint(0,10,5)
rand_array

array([7, 3, 9, 2, 4])

In [34]:
sample_array.min()

2

In [35]:
sample_array.argmin()

0

In [36]:
rand_array.min()

2

In [37]:
rand_array.argmin()

3

In [38]:
sample_array.max()

19

In [39]:
sample_array.argmax()

17

In [40]:
rand_array.max()

9

In [41]:
rand_array.argmax()

2

In [42]:
a=np.eye(5)

In [43]:
a



array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
a=np.random.rand(2,3)

In [45]:
a

array([[0.49473402, 0.91116101, 0.77609717],
       [0.50924201, 0.5651084 , 0.16734281]])

In [46]:
## transpose
a.T

array([[0.49473402, 0.50924201],
       [0.91116101, 0.5651084 ],
       [0.77609717, 0.16734281]])

In [47]:
sample_array=np.arange(10,28)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

In [48]:
### reshaping the array into different rowns and columns

sample_array=sample_array.reshape(6,3)

In [49]:
sample_array

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [50]:
sample_array=sample_array.reshape(3,6)

In [51]:
sample_array

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27]])

In [52]:
### cannot reshape 18 elements into 12 elements

sample_array=sample_array.reshape(3,4)

ValueError: cannot reshape array of size 18 into shape (3,4)

In [53]:
sample_array

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27]])

In [54]:
## transpose of a matrix

sample_array.T

array([[10, 16, 22],
       [11, 17, 23],
       [12, 18, 24],
       [13, 19, 25],
       [14, 20, 26],
       [15, 21, 27]])

In [56]:
#Changing all the elements of a specific ROW
# changing all the elements in row no.2 into 10

sample_array[2]=10

In [57]:
sample_array

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [10, 10, 10, 10, 10, 10]])

In [58]:
### changing all the elements in row 0 into 20

sample_array[0]=20

In [59]:
sample_array

array([[20, 20, 20, 20, 20, 20],
       [16, 17, 18, 19, 20, 21],
       [10, 10, 10, 10, 10, 10]])

In [60]:
sample_array=np.arange(10,100)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [61]:
### printing few elements from the sample_array
### [startindex:last index +1]

sample_array[1:12]
## from index 1 to index 11

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [62]:
sample_array[3:9]
## from index 3 to index 8

array([13, 14, 15, 16, 17, 18])

In [63]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [64]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

In [65]:
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001,   17,   18,   19,   20,
         21,   22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
         32,   33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
         43,   44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
         54,   55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
         65,   66,   67,   68,   69,   70,   71,   72,   73,   74,   75,
         76,   77,   78,   79,   80,   81,   82,   83,   84,   85,   86,
         87,   88,   89,   90,   91,   92,   93,   94,   95,   96,   97,
         98,   99])

In [66]:
sample_array= np.arange(10,100)

In [67]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [72]:
sa=np.array([[31,29,44],[62,19,65]])
sa 

array([[31, 29, 44],
       [62, 19, 65]])

In [73]:
sa[0,1]

29

In [74]:
sa[0]

array([31, 29, 44])

In [76]:
sa[1]

array([62, 19, 65])

In [77]:
sa[-1]

array([62, 19, 65])

In [78]:
sa[0][1]

29

In [81]:
aar=np.array([[2,6,8],[1,5,4],[4,3,2]])

In [82]:
aar

array([[2, 6, 8],
       [1, 5, 4],
       [4, 3, 2]])

In [84]:
aar[:,1]

array([6, 5, 3])

In [88]:
aar[1][1:]


## also can be written as
## aar[1,1:]

array([5, 4])

In [92]:
ara=np.array(([24,13,2,15],[15,2,54,65],[56,76,24,7]))
ara

array([[24, 13,  2, 15],
       [15,  2, 54, 65],
       [56, 76, 24,  7]])

In [93]:
ara[2][2]

24

In [94]:
ara[1][2]

54

In [95]:
ara[:,2]

array([ 2, 54, 24])

In [96]:
ara[1,1]

2

In [97]:
ara[1:3,2:4]

array([[54, 65],
       [24,  7]])

In [98]:
ara[1:,2:]

array([[54, 65],
       [24,  7]])

In [99]:
ara[2]

array([56, 76, 24,  7])

In [100]:
arra=np.arange(1,31)

In [101]:
arra

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [102]:
abc=np.arange(31,61)
abc

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [103]:
arra+abc

array([32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64,
       66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90])

In [104]:
arra

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [105]:
mcq=arra+abc

In [106]:
mcq

array([32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64,
       66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90])

In [107]:
np.exp(arra)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [108]:
np.sqrt(arra)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [109]:
np.log(arra)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [110]:
np.max(arra)

30

In [111]:
np.argmax(arra)

29

In [112]:
np.min(arra)

1

In [113]:
np.argmin(arra)

0

In [114]:
np.square(arra)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900], dtype=int32)

In [116]:
### standard deviation

np.std(arra)


8.65544144839919

In [117]:
### variance

np.var(arra)

74.91666666666667

In [118]:
###Mean

np.mean(arra)

15.5

In [119]:
array=np.random.rand(3,4)
array

### normal distribution

array([[0.76013713, 0.6349509 , 0.1639125 , 0.97808283],
       [0.44073032, 0.2913041 , 0.07742758, 0.10318398],
       [0.52852985, 0.69567996, 0.53592796, 0.39154442]])

In [120]:
np.round(array,decimals=3)

## round off uptill specified decimals

array([[0.76 , 0.635, 0.164, 0.978],
       [0.441, 0.291, 0.077, 0.103],
       [0.529, 0.696, 0.536, 0.392]])

In [121]:
sports=np.array(['golf','cricket','football','basketball', 'cricket'])
np.unique(sports)

### elements are not repeated

array(['basketball', 'cricket', 'football', 'golf'], dtype='<U10')